# .scrutinizer.yml
imports:
    - javascript
    - php

filter:
    excluded_paths:
        - 'build/*'
        - 'dev/*'
        - 'doc/*'
        - 'test/*'
        - 'htdocs/includes/*'
    paths: {  }
    
tools:
	# Similar code detection
    php_sim:
        enabled: true
        min_mass: 16
        filter:
            excluded_paths:
                - 'build/*'
                - 'dev/*'
                - 'doc/*'
                - 'test/*'
                - 'htdocs/includes/*'
            paths: {  }

	# php_depend
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'build/*'
                - 'dev/*'
                - 'doc/*'
                - 'test/*'
                - 'htdocs/includes/*'
            paths: {  }

	# php_analyzer
    php_analyzer:
        enabled: true
        extensions:
            - php
        dependency_paths: {  }
        filter:
            excluded_paths:
                - 'build/*'
                - 'dev/*'
                - 'doc/*'
                - 'test/*'
                - 'htdocs/includes/*'
            paths: {  }
        path_configs: {  }

	# change tracking
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            excluded_paths:
                - 'build/*'
                - 'dev/*'
                - 'doc/*'
                - 'test/*'
                - 'htdocs/includes/*'
            paths: {  }

	# Coding-Style / Bug Detection
    js_hint: true


before_commands: {  }
after_commands: {  }
artifacts: {  }
build_failure_conditions: {  }
