# This docker-compose.yml file is used to build and run Dolibarr
# in the current workspace
#
# Before build/run, define the variable HOST_USER_ID as following:
# $ export HOST_USER_ID=$(id -u)
# And then, you can run :
# $ docker-compose up

mariadb:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dolibarr

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
        PMA_HOST: mariadb
    links:
        - mariadb
    ports:
        - "8080:80"

web:
    build: .
    environment:
        HOST_USER_ID: $HOST_USER_ID
    volumes:
        - ./htdocs:/var/www/html
    links:
        - mariadb
    ports:
        - "80:80"
